"""HTML report generation for backtest results.

Produces a self-contained HTML file with inline CSS and SVG charts.
No external dependencies beyond the Python standard library.
"""

from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path
from typing import Any

import structlog

logger = structlog.get_logger(__name__)


class BacktestReport:
    """Generate a self-contained HTML report from backtest results.

    Parameters
    ----------
    result:
        A :class:`BacktestResult` (or duck-typed object with ``equity_curve``,
        ``timestamps``, ``trades``, ``metrics``, ``portfolio_snapshots``).
    analytics:
        Dict of computed analytics (output of
        :meth:`BacktestAnalytics.compute_all`).
    """

    def __init__(self, result: Any, analytics: dict) -> None:
        self._result = result
        self._analytics = analytics

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_html(self, output_path: str) -> str:
        """Write the HTML report to *output_path* and return the path."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        content = self._build_html()
        path.write_text(content, encoding="utf-8")
        logger.info("backtest_report.generated", path=str(path))
        return str(path)

    # ------------------------------------------------------------------
    # HTML assembly
    # ------------------------------------------------------------------

    def _build_html(self) -> str:
        strategy_name = self._analytics.get("strategy_name", "Backtest")
        start = self._result.timestamps[0] if self._result.timestamps else ""
        end = self._result.timestamps[-1] if self._result.timestamps else ""
        generated = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{_esc(strategy_name)} - Backtest Report</title>
<style>{_CSS}</style>
</head>
<body>
<div class="container">
  {self._header_section(strategy_name, start, end, generated)}
  {self._key_metrics_section()}
  {self._equity_chart_section()}
  {self._drawdown_chart_section()}
  {self._metrics_table_section()}
  {self._trade_log_section()}
  <footer><p>Generated by Stock Trader Backtesting Engine</p></footer>
</div>
</body>
</html>"""

    # ------------------------------------------------------------------
    # Sections
    # ------------------------------------------------------------------

    def _header_section(
        self, name: str, start: Any, end: Any, generated: str,
    ) -> str:
        total_ret = self._analytics.get("total_return", 0.0)
        sharpe = self._analytics.get("sharpe_ratio", 0.0)
        max_dd = self._analytics.get("max_drawdown", 0.0)

        return f"""
<header>
  <h1>{_esc(name)}</h1>
  <p class="sub">{start} &mdash; {end} | Generated {generated}</p>
  <div class="kpi-row">
    <div class="kpi">
      <span class="kpi-label">Total Return</span>
      <span class="kpi-value {_color_class(total_ret)}">{total_ret:+.2%}</span>
    </div>
    <div class="kpi">
      <span class="kpi-label">Sharpe Ratio</span>
      <span class="kpi-value">{sharpe:.2f}</span>
    </div>
    <div class="kpi">
      <span class="kpi-label">Max Drawdown</span>
      <span class="kpi-value negative">-{max_dd:.2%}</span>
    </div>
  </div>
</header>"""

    def _key_metrics_section(self) -> str:
        metrics = [
            ("Annualized Return", self._analytics.get("annualized_return", 0.0), True),
            ("Volatility", self._analytics.get("volatility", 0.0), True),
            ("Sortino Ratio", self._analytics.get("sortino_ratio", 0.0), False),
            ("Calmar Ratio", self._analytics.get("calmar_ratio", 0.0), False),
            ("Win Rate", self._analytics.get("win_rate", 0.0), True),
            ("Profit Factor", self._analytics.get("profit_factor", 0.0), False),
            ("Total Trades", self._analytics.get("total_trades", 0), False),
        ]
        rows = ""
        for label, value, is_pct in metrics:
            if is_pct and isinstance(value, float):
                formatted = f"{value:.2%}"
            elif isinstance(value, float):
                formatted = f"{value:.2f}"
            else:
                formatted = str(value)
            rows += f"<tr><td>{label}</td><td>{formatted}</td></tr>\n"

        return f"""
<section>
  <h2>Key Metrics</h2>
  <table class="metrics"><tbody>{rows}</tbody></table>
</section>"""

    def _equity_chart_section(self) -> str:
        if not self._result.equity_curve:
            return "<section><h2>Equity Curve</h2><p>No data.</p></section>"
        svg = _line_chart_svg(
            self._result.equity_curve,
            title="Equity Curve",
            color="#2563eb",
        )
        return f"<section><h2>Equity Curve</h2>{svg}</section>"

    def _drawdown_chart_section(self) -> str:
        equity = self._result.equity_curve
        if len(equity) < 2:
            return "<section><h2>Drawdown</h2><p>No data.</p></section>"

        # Compute drawdown series.
        peak = equity[0]
        dd_series: list[float] = [0.0]
        for v in equity[1:]:
            if v > peak:
                peak = v
            dd_series.append(-((peak - v) / peak) if peak > 0 else 0.0)

        svg = _line_chart_svg(
            dd_series,
            title="Drawdown",
            color="#dc2626",
            fill=True,
        )
        return f"<section><h2>Drawdown</h2>{svg}</section>"

    def _metrics_table_section(self) -> str:
        rows = ""
        for key, value in sorted(self._analytics.items()):
            if key == "strategy_name":
                continue
            if isinstance(value, float):
                formatted = f"{value:.4f}"
            else:
                formatted = str(value)
            rows += f"<tr><td>{_esc(key)}</td><td>{_esc(formatted)}</td></tr>\n"
        return f"""
<section>
  <h2>All Metrics</h2>
  <table class="metrics"><tbody>{rows}</tbody></table>
</section>"""

    def _trade_log_section(self, max_trades: int = 100) -> str:
        trades = self._result.trades
        if not trades:
            return "<section><h2>Trade Log</h2><p>No trades recorded.</p></section>"

        header_cols = ["#", "Symbol", "Side", "Qty", "Entry", "Exit", "PnL"]
        header = "".join(f"<th>{c}</th>" for c in header_cols)

        rows = ""
        for i, t in enumerate(trades[:max_trades], 1):
            pnl = t.get("pnl", 0.0)
            pnl_class = "positive" if pnl > 0 else "negative" if pnl < 0 else ""
            rows += (
                f"<tr>"
                f"<td>{i}</td>"
                f"<td>{_esc(str(t.get('symbol', '')))}</td>"
                f"<td>{_esc(str(t.get('side', '')))}</td>"
                f"<td>{t.get('quantity', '')}</td>"
                f"<td>{_esc(str(t.get('entry_price', '')))}</td>"
                f"<td>{_esc(str(t.get('exit_price', '')))}</td>"
                f"<td class=\"{pnl_class}\">{pnl:+.2f}</td>"
                f"</tr>\n"
            )

        note = ""
        if len(trades) > max_trades:
            note = f"<p class='sub'>Showing first {max_trades} of {len(trades)} trades.</p>"

        return f"""
<section>
  <h2>Trade Log</h2>
  {note}
  <table class="trades">
    <thead><tr>{header}</tr></thead>
    <tbody>{rows}</tbody>
  </table>
</section>"""


# ======================================================================
# Inline SVG chart helper
# ======================================================================

def _line_chart_svg(
    values: list[float],
    *,
    title: str = "",
    color: str = "#2563eb",
    width: int = 800,
    height: int = 250,
    fill: bool = False,
) -> str:
    """Render a simple line chart as an inline SVG string."""
    if not values:
        return "<p>No data.</p>"

    margin_left = 70
    margin_right = 20
    margin_top = 20
    margin_bottom = 30
    plot_w = width - margin_left - margin_right
    plot_h = height - margin_top - margin_bottom

    v_min = min(values)
    v_max = max(values)
    v_range = v_max - v_min if v_max != v_min else 1.0

    n = len(values)
    step = plot_w / max(n - 1, 1)

    points: list[str] = []
    for i, v in enumerate(values):
        x = margin_left + i * step
        y = margin_top + plot_h - ((v - v_min) / v_range) * plot_h
        points.append(f"{x:.1f},{y:.1f}")

    polyline = " ".join(points)

    fill_path = ""
    if fill:
        bottom_y = margin_top + plot_h
        fill_path = (
            f'<polygon points="{margin_left:.1f},{bottom_y:.1f} '
            f'{polyline} '
            f'{margin_left + (n - 1) * step:.1f},{bottom_y:.1f}" '
            f'fill="{color}" fill-opacity="0.15" />'
        )

    # Y-axis labels.
    y_labels = ""
    for frac in [0.0, 0.25, 0.5, 0.75, 1.0]:
        val = v_min + frac * v_range
        y = margin_top + plot_h - frac * plot_h
        if abs(val) >= 1000:
            label = f"{val:,.0f}"
        elif abs(val) >= 1:
            label = f"{val:.2f}"
        else:
            label = f"{val:.4f}"
        y_labels += (
            f'<text x="{margin_left - 5}" y="{y:.1f}" '
            f'text-anchor="end" font-size="10" fill="#666">{label}</text>'
        )
        y_labels += (
            f'<line x1="{margin_left}" y1="{y:.1f}" '
            f'x2="{width - margin_right}" y2="{y:.1f}" '
            f'stroke="#eee" stroke-width="1" />'
        )

    return (
        f'<svg viewBox="0 0 {width} {height}" '
        f'xmlns="http://www.w3.org/2000/svg" class="chart">'
        f"{y_labels}"
        f"{fill_path}"
        f'<polyline points="{polyline}" fill="none" '
        f'stroke="{color}" stroke-width="1.5" />'
        f"</svg>"
    )


# ======================================================================
# Utilities
# ======================================================================

def _esc(text: str) -> str:
    return html.escape(str(text))


def _color_class(value: float) -> str:
    if value > 0:
        return "positive"
    if value < 0:
        return "negative"
    return ""


# ======================================================================
# Inline CSS
# ======================================================================

_CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
       'Helvetica Neue', sans-serif; background: #f8fafc; color: #1e293b;
       line-height: 1.6; }
.container { max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
header { margin-bottom: 2rem; padding: 1.5rem; background: #fff;
         border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
h2 { font-size: 1.2rem; margin-bottom: 1rem; color: #334155; }
.sub { color: #64748b; font-size: 0.85rem; }
.kpi-row { display: flex; gap: 2rem; margin-top: 1rem; flex-wrap: wrap; }
.kpi { display: flex; flex-direction: column; }
.kpi-label { font-size: 0.75rem; text-transform: uppercase; color: #64748b;
             letter-spacing: 0.05em; }
.kpi-value { font-size: 1.5rem; font-weight: 700; }
.positive { color: #16a34a; }
.negative { color: #dc2626; }
section { margin-bottom: 2rem; padding: 1.5rem; background: #fff;
          border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
table th, table td { padding: 0.5rem 0.75rem; text-align: left;
                     border-bottom: 1px solid #e2e8f0; }
table th { background: #f1f5f9; font-weight: 600; }
.chart { width: 100%; height: auto; }
footer { text-align: center; padding: 1rem; color: #94a3b8;
         font-size: 0.75rem; }
"""
